# note theme: jekyll-theme-minimal is still needed eventhough I have my own default.html master file.
# it is needed because all of the CSS and other supporting files are loaded with this "theme:" statement
version: 1.01
theme: jekyll-theme-minimal
timezone: America/New_York
title: Empire Millennium Chrome Extension
description: >- # this means to ignore newlines until "baseurl:"
  Generic Chrome Extension utility for the game Empire Millennium Wars.
show_downloads: true
# image is for seo image (meta="og:image"), logo is in _default template. (left logo for back compatibility)
image: images/logo.jpg 
logo: images/logo.jpg
# yet another attempt to get SEO og:image meta tag to auto show up:
defaults:
 - scope:
     path: ""
   values:
     image: images/logo.jpg
google_analytics: UA-127176852-1
favicon_url: "https://assets-cdn.github.com/favicon.ico"
future: true
destination: ./_site
github_username:  sflanders95
exclude:
  - Gemfile
  - Gemfile.lock
  - 'manifest.json'
  - 'package.sh'
  - 'serve.sh'
  - 'tmp'
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# testing sln from https://github.community/t5/GitHub-Pages/gitHub-pages-URL-404/m-p/4466#M341
# thest did not help viewing https://sflanders95.github.io/EmpireMillenniumChatBlockerChromeExt/docs/test.html
# include: [/docs]
# include: /docs
# include: docs
